"""algo_codegen — emit a general-algorithm op as standalone Python and C.

Mirrors the image ``codegen.py`` philosophy for the general tier (``algo.py``):

  emit_python(op) : a standalone module defining ``run(a)`` — the same body the
                    in-process reference is compiled from (single source of truth).
  emit_c(op)      : a complete, compilable C program = the op's C function plus a
                    binary-I/O driver, so ``algo_difftest`` can compile, run, and
                    compare it bit-for-bit to the Python reference.

Binary protocol (native endianness — writer and reader run on the same machine):

  input  : int32 n_arrays, then per array {int32 len, len * float64}
  output : int32 n_arrays, then
             sort  (out_sort == SEQ)    : per array {int32 len, len * float64}
             reduce(out_sort == SCALAR) : n_arrays * float64

The exact same protocol is implemented on the Python side in ``algo_difftest`` —
keeping both here in one docstring is deliberate so a change to one is a visible
change to the other.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import algo

_HEADER_PY = '"""Generated by fullseye algo_codegen — do not edit. Reference: pure Python."""'
_HEADER_C = "/* Generated by fullseye algo_codegen — do not edit. Backend: C. */"


def emit_python(op: algo.AlgoOp) -> str:
    """Standalone Python defining ``run(a)`` for ``op`` (a list-in / list-or-float-out)."""
    return _HEADER_PY + "\n\n" + op.py_code


def _driver_c(op: algo.AlgoOp) -> str:
    """The binary-I/O ``main`` for ``op`` (tailored to sort vs reduce)."""
    if op.kind == algo.KIND_SORT:
        per_array_call = f"        {op.c_func}(buf, len);\n"
        write_out = (
            "        if (fwrite(&len, sizeof(int), 1, fo) != 1) return 4;\n"
            "        if (len > 0 && fwrite(buf, sizeof(double), (size_t)len, fo) != (size_t)len) return 4;\n"
        )
    elif op.kind == algo.KIND_REDUCE:
        per_array_call = f"        double r = {op.c_func}(buf, len);\n"
        write_out = "        if (fwrite(&r, sizeof(double), 1, fo) != 1) return 4;\n"
    else:  # fail-closed: an unknown kind must not silently emit a no-op driver
        raise ValueError(f"unknown algo op kind {op.kind!r}")

    return (
        "int main(int argc, char** argv) {\n"
        '    if (argc < 3) { fprintf(stderr, "usage: %s in.bin out.bin\\n", argv[0]); return 1; }\n'
        '    FILE* fi = fopen(argv[1], "rb");\n'
        '    FILE* fo = fopen(argv[2], "wb");\n'
        "    if (!fi || !fo) return 2;\n"
        "    int n_arrays = 0;\n"
        "    if (fread(&n_arrays, sizeof(int), 1, fi) != 1) return 3;\n"
        "    if (fwrite(&n_arrays, sizeof(int), 1, fo) != 1) return 4;\n"
        "    for (int t = 0; t < n_arrays; t++) {\n"
        "        int len = 0;\n"
        "        if (fread(&len, sizeof(int), 1, fi) != 1) return 3;\n"
        "        if (len < 0) return 5;\n"
        "        double* buf = (double*)malloc((size_t)(len > 0 ? len : 1) * sizeof(double));\n"
        "        if (!buf) return 6;\n"
        "        if (len > 0 && fread(buf, sizeof(double), (size_t)len, fi) != (size_t)len) return 3;\n"
        + per_array_call
        + write_out
        + "        free(buf);\n"
        "    }\n"
        "    fclose(fi); fclose(fo);\n"
        "    return 0;\n"
        "}\n"
    )


def emit_c(op: "algo.AlgoOp") -> str:
    """A complete, compilable C program: the op's function + a binary-I/O driver."""
    parts = [
        _HEADER_C,
        "#include <stdio.h>",
        "#include <stdlib.h>",
        "",
        op.c_code.rstrip(),
        "",
        _driver_c(op),
    ]
    return "\n".join(parts)


def emit(name: str, wd: Path) -> dict:
    """Write ``gen_<name>.py`` and ``gen_<name>.c`` for op ``name`` into ``wd``.

    Returns a codegen-info dict (mirrors image ``codegen.emit``): both backends are
    always fully supported here, since ``algo`` ops ship both a Python and a C
    reference by construction.
    """
    op = algo.ALGO_BY_NAME[name]             # KeyError (fail-closed) for unknown ops
    wd = Path(wd)
    wd.mkdir(parents=True, exist_ok=True)
    py_path = wd / f"gen_{name}.py"
    c_path = wd / f"gen_{name}.c"
    py_path.write_text(emit_python(op), encoding="utf-8")
    c_path.write_text(emit_c(op), encoding="utf-8")
    return {
        "op": name, "category": op.category, "kind": op.kind,
        "in_sort": op.in_sort, "out_sort": op.out_sort, "c_func": op.c_func,
        "provenance": op.provenance, "c_fully_supported": True,
        "py": str(py_path), "c": str(c_path),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--op", default="quicksort", choices=algo.algo_names() + ["all"])
    ap.add_argument("--workdir", default="out/algo")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    wd = Path(a.workdir)
    names = algo.algo_names() if a.op == "all" else [a.op]
    infos = [emit(n, wd) for n in names]
    payload = infos[0] if len(infos) == 1 else {"ops": infos}
    (wd / "algo_codegen.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    if a.out:
        p = a.out if a.out.endswith(".json") else a.out + ".json"
        Path(p).write_text(json.dumps(payload, indent=2), encoding="utf-8")
    for info in infos:
        print(f"[algo_codegen:{info['op']}] {info['kind']} -> {info['py']} , {info['c']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
