"""Generated wheel-shippable mirror of data/auto_specs/*.json — DO NOT hand-edit.

Written by gen_auto_specs_data.py. backends_auto.load_specs() reads this when the
flat-layout data/auto_specs/ dir is absent (a pip-installed wheel), so the data-driven
auto ops register on an installed package, not only in the editable source tree."""
from __future__ import annotations

AUTO_SPECS = [{'halcon': 'tan_image',
  'category': 'arithmetic',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'pointwise',
  'params': {'func': 'tan'}},
 {'halcon': 'bit_not',
  'category': 'gray',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'lut',
  'params': {'kind': 'invert'}},
 {'halcon': 'monotony',
  'category': 'gray',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'lut',
  'params': {'kind': 'monotony'}},
 {'halcon': 'eliminate_min_max',
  'category': 'rank',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'rank',
  'params': {'kind': 'median'}},
 {'halcon': 'median_weighted',
  'category': 'rank',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'rank',
  'params': {'kind': 'median'}},
 {'halcon': 'mean_sp',
  'category': 'rank',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'rank',
  'params': {'kind': 'trimmed_mean'}},
 {'halcon': 'eliminate_sp',
  'category': 'rank',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'rank',
  'params': {'kind': 'sigma'}},
 {'halcon': 'simulate_defocus',
  'category': 'smoothing',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'linfilter',
  'params': {'kind': 'mean'}},
 {'halcon': 'dots_image',
  'category': 'edges',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'linfilter',
  'params': {'kind': 'laplace_gauss'}},
 {'halcon': 'frei_dir',
  'category': 'edges',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'edge',
  'params': {'kind': 'frei_dir'}},
 {'halcon': 'robinson_dir',
  'category': 'edges',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'edge',
  'params': {'kind': 'robinson_dir'}},
 {'halcon': 'fft_generic',
  'category': 'frequency',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'freq',
  'params': {'kind': 'fft_power'}},
 {'halcon': 'power_ln',
  'category': 'frequency',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'freq',
  'params': {'kind': 'fft_power'}},
 {'halcon': 'rft_generic',
  'category': 'frequency',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'freq',
  'params': {'kind': 'fft_power_real'}},
 {'halcon': 'phase_deg',
  'category': 'frequency',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'freq',
  'params': {'kind': 'fft_phase'}},
 {'halcon': 'affine_trans_image_size',
  'category': 'geometry',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'geom',
  'params': {'kind': 'affine'}},
 {'halcon': 'polar_trans_image_ext',
  'category': 'geometry',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'geom',
  'params': {'kind': 'polar'}},
 {'halcon': 'lines_facet',
  'category': 'contour',
  'in_sort': 'image',
  'out_sort': 'contour',
  'shape': 'xld',
  'params': {'kind': 'lines_gauss'}},
 {'halcon': 'add_noise_distribution',
  'category': 'noise',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'noise',
  'params': {'kind': 'gaussian'}},
 {'halcon': 'bin_threshold',
  'category': 'segmentation',
  'in_sort': 'image',
  'out_sort': 'region',
  'shape': 'threshold',
  'params': {'method': 'otsu'}},
 {'halcon': 'erosion_golay',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'binmorph',
  'params': {'op': 'erosion', 'shape': 'disk'}},
 {'halcon': 'dilation_golay',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'binmorph',
  'params': {'op': 'dilation', 'shape': 'disk'}},
 {'halcon': 'opening_golay',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'binmorph',
  'params': {'op': 'opening', 'shape': 'disk'}},
 {'halcon': 'closing_golay',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'binmorph',
  'params': {'op': 'closing', 'shape': 'disk'}},
 {'halcon': 'erosion_seq',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'binmorph',
  'params': {'op': 'erosion_it'}},
 {'halcon': 'dilation_seq',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'binmorph',
  'params': {'op': 'dilation_it'}},
 {'halcon': 'morph_skeleton',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'region_trans',
  'params': {'kind': 'skeleton'}},
 {'halcon': 'thinning_golay',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'region_trans',
  'params': {'kind': 'thin'}},
 {'halcon': 'thinning_seq',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'region_trans',
  'params': {'kind': 'thin'}},
 {'halcon': 'gray_erosion_shape',
  'category': 'morphology',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'graymorph',
  'params': {'op': 'erosion', 'shape': 'disk'}},
 {'halcon': 'gray_dilation_shape',
  'category': 'morphology',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'graymorph',
  'params': {'op': 'dilation', 'shape': 'disk'}},
 {'halcon': 'gray_opening_rect',
  'category': 'morphology',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'graymorph',
  'params': {'op': 'opening', 'shape': 'rect'}},
 {'halcon': 'gray_closing_rect',
  'category': 'morphology',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'graymorph',
  'params': {'op': 'closing', 'shape': 'rect'}},
 {'halcon': 'dual_rank',
  'category': 'rank',
  'in_sort': 'image',
  'out_sort': 'image',
  'shape': 'rank',
  'params': {'kind': 'rank'}},
 {'halcon': 'fast_threshold',
  'category': 'segmentation',
  'in_sort': 'image',
  'out_sort': 'region',
  'shape': 'threshold',
  'params': {'method': 'fixed'}},
 {'halcon': 'nonmax_suppression_amp',
  'category': 'segmentation',
  'in_sort': 'image',
  'out_sort': 'region',
  'shape': 'segment',
  'params': {'kind': 'local_max'}},
 {'halcon': 'pouring',
  'category': 'segmentation',
  'in_sort': 'image',
  'out_sort': 'region',
  'shape': 'segment',
  'params': {'kind': 'watershed'}},
 {'halcon': 'affine_trans_region',
  'category': 'geometry',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'geom',
  'params': {'kind': 'affine'}},
 {'halcon': 'mirror_region',
  'category': 'geometry',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'geom',
  'params': {'kind': 'mirror'}},
 {'halcon': 'zoom_region',
  'category': 'geometry',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'geom',
  'params': {'kind': 'zoom'}},
 {'halcon': 'fill_up_shape',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'region_trans',
  'params': {'kind': 'remove_holes'}},
 {'halcon': 'remove_noise_region',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'binmorph',
  'params': {'op': 'opening', 'shape': 'disk'}},
 {'halcon': 'smallest_rectangle1',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'region_trans',
  'params': {'kind': 'shape_bbox'}},
 {'halcon': 'get_region_contour',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'region_trans',
  'params': {'kind': 'boundary'}},
 {'halcon': 'get_region_convex',
  'category': 'region',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'region_trans',
  'params': {'kind': 'convex'}},
 {'halcon': 'gen_region_polygon_xld',
  'category': 'contour',
  'in_sort': 'contour',
  'out_sort': 'region',
  'shape': 'xld',
  'params': {'kind': 'to_region'}},
 {'halcon': 'connect_and_holes',
  'category': 'features',
  'in_sort': 'region',
  'out_sort': 'feature',
  'shape': 'region_feat',
  'params': {'metric': 'count'}},
 {'halcon': 'elliptic_axis',
  'category': 'features',
  'in_sort': 'region',
  'out_sort': 'feature',
  'shape': 'region_feat',
  'params': {'metric': 'anisometry'}},
 {'halcon': 'polar_trans_region_inv',
  'category': 'geometry',
  'in_sort': 'region',
  'out_sort': 'region',
  'shape': 'geom',
  'params': {'kind': 'polar_inv'}},
 {'halcon': 'affine_trans_polygon_xld',
  'category': 'contour',
  'in_sort': 'contour',
  'out_sort': 'contour',
  'shape': 'xld',
  'params': {'kind': 'affine'}},
 {'halcon': 'gen_contour_region_xld',
  'category': 'contour',
  'in_sort': 'region',
  'out_sort': 'contour',
  'shape': 'xld',
  'params': {'kind': 'region_boundary'}},
 {'halcon': 'select_shape_xld',
  'category': 'contour',
  'in_sort': 'contour',
  'out_sort': 'contour',
  'shape': 'xld',
  'params': {'kind': 'select_contours'}},
 {'halcon': 'contour_point_num_xld',
  'category': 'contour',
  'in_sort': 'contour',
  'out_sort': 'feature',
  'shape': 'xld',
  'params': {'kind': 'num_points'}}]
