"""S2 — multi-backend codegen from the typed IR (registry-driven, auto-scaling).

Emits the champion pipeline as standalone source in two backends:

  gen_<problem>.py : calls the shared Python runtime (ops.RT) with params baked in.
                     Works for EVERY registered op automatically.
  gen_<problem>.c  : calls the imgops C runtime — only for ops that declare a C
                     statement (op.c_stmt). Ops without one are marked unsupported
                     (honest), so difftest.py knows whether the C path is complete.

Because operators live in one registry with their own codegen, adding an operator
needs no change here — Python codegen scales for free; C scales as the runtime grows.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import ops

_OPMAP = {op.name: op for op in ops.REGISTRY}


def emit(problem: str, wd: Path) -> dict:
    champ = json.loads((wd / f"champion_{problem}.json").read_text(encoding="utf-8"))
    stages = ops.decode(champ["genome"])

    # --- Python backend (every op) --------------------------------------- #
    py = ['"""Generated by imgevolve codegen — do not edit. Backend: numpy (ops.RT)."""',
          "import numpy as np", "import ops", "",
          "def pipeline(x):", "    x = x.astype(np.float64)"]
    for s in stages:
        if s.op == "identity":
            py.append("    # identity")
        else:
            op = _OPMAP[s.op]
            call = f"ops.RT[{s.op!r}](x, {s.a:.6f}, {s.b:.6f})"
            # Only clip pixel outputs to [0,1]. Clipping a feature (a scalar
            # measurement) or a contour (a dict) would silently destroy it — e.g.
            # a blob count of 7 clamped to 1.0. Emit those raw.
            if op.out_sort in ("image", "region"):
                py.append(f"    x = np.clip({call}, 0.0, 1.0)")
            else:
                py.append(f"    x = {call}  # out_sort={op.out_sort}: raw (no [0,1] clip)")
    py += ["    return x", ""]
    (wd / f"gen_{problem}.py").write_text("\n".join(py), encoding="utf-8")

    # --- C backend (ops with a C statement) ------------------------------ #
    c_ok = all((s.op == "identity") or (_OPMAP[s.op].c_stmt is not None) for s in stages)
    c = ['/* Generated by imgevolve codegen — do not edit. Backend: C (imgops runtime). */',
         '#include "imgops.h"', "", "void pipeline(float* buf, int w, int h) {"]
    for s in stages:
        op = _OPMAP[s.op]
        if s.op == "identity":
            c.append("    /* identity */")
        elif op.c_stmt is not None:
            c.append("    " + op.c_stmt(s.a, s.b))
        else:
            c.append(f"    /* op '{s.op}' ({op.halcon}) not yet in the C runtime — compile-gated */")
    c += ["}", ""]
    (wd / f"gen_{problem}.c").write_text("\n".join(c), encoding="utf-8")

    used = [s.op for s in stages if s.op != "identity"]
    return {"problem": problem, "pipeline": champ["pipeline"], "n_stages": len(stages),
            "ops_used": used, "c_fully_supported": c_ok,
            "py": str(wd / f"gen_{problem}.py"), "c": str(wd / f"gen_{problem}.c")}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--problem", default="edge")
    ap.add_argument("--workdir", default="out/worklog/imgevolve")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    wd = Path(a.workdir)
    info = emit(a.problem, wd)
    (wd / f"codegen_{a.problem}.json").write_text(json.dumps(info, indent=2), encoding="utf-8")
    if a.out:
        p = a.out if a.out.endswith(".json") else a.out + ".json"
        Path(p).write_text(json.dumps(info, indent=2), encoding="utf-8")
    print(f"[codegen:{a.problem}] {info['n_stages']} stages, C-fully-supported={info['c_fully_supported']} "
          f"-> {info['py']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
