"""S2 — multi-backend codegen from the typed IR.

Reads champion_<problem>.json and emits the pipeline as standalone source in two
backends:

  - gen_<problem>.py : self-contained numpy/scipy module (runnable now)
  - gen_<problem>.c  : C using the shipped imgops runtime (compile-gated on a
                       C toolchain; see difftest.py)

The point of emitting from a *typed IR* (rather than evolving raw source à la
AlphaEvolve) is that the same champion targets many languages by construction, and
difftest.py can verify the backends agree (the honest-correctness gate). Each op has
a clean per-language mapping; params are baked in as literals.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import ops

# per-op code templates. a,b are the decoded params (floats in [0,1]).
# python lines operate on `x`; C lines call imgops functions on (buf,w,h).
_C_SUPPORTED = {"identity", "gaussian", "uniform", "gamma", "threshold", "sharpen", "sobel_mag"}


def _py_line(st: ops.Stage) -> str:
    a, b = st.a, st.b
    op = st.op
    if op == "identity":
        return "    # identity"
    if op == "gaussian":
        return f"    x = ndimage.gaussian_filter(x, sigma={0.3 + 2.7 * a:.6f})"
    if op == "median":
        return f"    x = ndimage.median_filter(x, size={(3, 5, 7)[min(2, int(a * 3))]})"
    if op == "uniform":
        return f"    x = ndimage.uniform_filter(x, size={3 + 2 * int(a * 3)})"
    if op == "gamma":
        return f"    x = np.clip(x, 0, 1) ** {0.5 + 1.5 * a:.6f}"
    if op == "sharpen":
        return (f"    x = x + {1.5 * a:.6f} * (x - ndimage.gaussian_filter(x, sigma={0.5 + 1.5 * b:.6f}))")
    if op == "bilateral":
        return f"    x = _bilateral(x, {1.0 + 3.0 * a:.6f}, {0.05 + 0.4 * b:.6f})"
    if op == "sobel_mag":
        return "    x = _sobel_mag(x)"
    if op == "threshold":
        return f"    x = (x > {a:.6f}).astype(np.float64)"
    if op == "otsu":
        return "    x = _otsu(x)"
    if op == "morph_open":
        return f"    x = ndimage.grey_opening(x, size={3 + 2 * int(a * 3)})"
    if op == "morph_close":
        return f"    x = ndimage.grey_closing(x, size={3 + 2 * int(a * 3)})"
    return f"    # UNKNOWN op {op}"


_PY_HELPERS = '''
def _bilateral(img, ss, sr):
    r = 2; import numpy as np
    out = np.zeros_like(img, np.float64); wsum = np.zeros_like(img, np.float64)
    for dy in range(-r, r + 1):
        for dx in range(-r, r + 1):
            sh = np.roll(np.roll(img, dy, 0), dx, 1)
            w = np.exp(-(dx*dx+dy*dy)/(2*ss*ss)) * np.exp(-((sh-img)**2)/(2*sr*sr))
            out += w*sh; wsum += w
    return out/np.maximum(wsum, 1e-8)


def _sobel_mag(img):
    from scipy import ndimage; import numpy as np
    m = np.hypot(ndimage.sobel(img, 1), ndimage.sobel(img, 0)); mx = float(m.max())
    return m/mx if mx > 1e-8 else m


def _otsu(img):
    import numpy as np
    x = np.clip(img, 0, 1); hist, edges = np.histogram(x, 256, (0, 1))
    p = hist.astype(np.float64)/max(1, hist.sum()); omega = np.cumsum(p)
    mids = (edges[:-1]+edges[1:])/2; mu = np.cumsum(p*mids); mu_t = mu[-1]
    den = omega*(1-omega); sb = np.where(den > 1e-12, (mu_t*omega-mu)**2/np.maximum(den, 1e-12), 0.0)
    return (x > mids[int(np.argmax(sb))]).astype(np.float64)
'''


def _c_line(st: ops.Stage) -> str:
    a, b = st.a, st.b
    op = st.op
    if op == "identity":
        return "    /* identity */"
    if op == "gaussian":
        return f"    gaussian(buf, w, h, {0.3 + 2.7 * a:.6f}f);"
    if op == "uniform":
        return f"    box(buf, w, h, {3 + 2 * int(a * 3)});"
    if op == "gamma":
        return f"    gamma_op(buf, w, h, {0.5 + 1.5 * a:.6f}f);"
    if op == "threshold":
        return f"    threshold(buf, w, h, {a:.6f}f);"
    if op == "sharpen":
        return f"    sharpen(buf, w, h, {1.5 * a:.6f}f, {0.5 + 1.5 * b:.6f}f);"
    if op == "sobel_mag":
        return "    sobel_mag(buf, w, h);"
    return f"    /* op '{op}' not yet in the C runtime (compile-gated) */"


def emit(problem: str, wd: Path) -> dict:
    champ = json.loads((wd / f"champion_{problem}.json").read_text(encoding="utf-8"))
    stages = ops.decode(champ["genome"])
    c_ok = all(s.op in _C_SUPPORTED for s in stages)

    py = ['"""Generated by imgevolve codegen — do not edit. Backend: numpy/scipy."""',
          "import numpy as np", "from scipy import ndimage", _PY_HELPERS,
          "", "def pipeline(x):", '    """x: float64 HxW in [0,1] -> denoised/segmented HxW."""',
          "    x = x.astype(np.float64)"]
    py += [_py_line(s) for s in stages]
    py += ["    return np.clip(x, 0.0, 1.0)", ""]
    (wd / f"gen_{problem}.py").write_text("\n".join(py), encoding="utf-8")

    c = ['/* Generated by imgevolve codegen — do not edit. Backend: C (imgops runtime). */',
         '#include "imgops.h"', "",
         "void pipeline(float* buf, int w, int h) {"]
    c += [_c_line(s) for s in stages]
    c += ["}", ""]
    (wd / f"gen_{problem}.c").write_text("\n".join(c), encoding="utf-8")

    return {"problem": problem, "pipeline": champ["pipeline"], "n_stages": len(stages),
            "c_fully_supported": c_ok,
            "py": str(wd / f"gen_{problem}.py"), "c": str(wd / f"gen_{problem}.c")}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--problem", default="edge")
    ap.add_argument("--workdir", default="out/worklog/imgevolve")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    wd = Path(a.workdir)
    info = emit(a.problem, wd)
    (wd / f"codegen_{a.problem}.json").write_text(json.dumps(info, indent=2), encoding="utf-8")
    if a.out:
        p = a.out if a.out.endswith(".json") else a.out + ".json"
        Path(p).write_text(json.dumps(info, indent=2), encoding="utf-8")
    print(f"[codegen:{a.problem}] emitted Python + C ({info['n_stages']} stages, "
          f"C-fully-supported={info['c_fully_supported']}) -> {info['py']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
