# -*- coding: utf-8 -*-
"""文献層 ``docs/literature/`` の門(2026-09-21)。

文献層は「知識 → **どの op を使うか**」に落ちて初めて RAG の土台になる(ユーザー: fullseye の RAG は op を
有効に使うための土台)。この門は生成物の**形**を守る —— コーパス本体は repo に無いので中身の再生成は見られないが、

1. 各文献層の **op リンクが実在のノートを指す**(消えた op・改名した op を指したまま公開しない)
2. 上位クラスタの全部に「使う op の候補」節があり、全体で op リンクがゼロでない(空の文献層を黙って出さない)
3. **抄録を写していない**(``## Abstract`` が無い)・**手元の絶対パスが無い**(``C:\\`` / ``C:/`` / ``/c/``)
4. INDEX の行と各ファイルの件数(クラスタ・葉)が一致する(自己記述が実態から離れない)
5. INDEX から各ファイルへ辿れ、docs の全体地図(README)から INDEX へ辿れる
"""
from __future__ import annotations

import os
import re

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIT = os.path.join(ROOT, "docs", "literature")
_MARK = "generated by tools/gen_literature_notes.py from the RAD corpus"
#: 文献層(コーパス由来)のファイルだけ。OSS の地図(OSS_LANDSCAPE.md)は別の生成器で、形が違うので別の門
FILES = sorted(f for f in os.listdir(LIT) if f.endswith(".md") and f != "INDEX.md"
               and _MARK in open(os.path.join(LIT, f), encoding="utf-8").read(2000)) if os.path.isdir(LIT) else []


def _read(name: str) -> str:
    with open(os.path.join(LIT, name), encoding="utf-8") as f:
        return f.read()


def test_the_layer_exists_and_is_listed():
    assert FILES, "docs/literature/ に文献層が 1 本も無い"
    index = _read("INDEX.md")
    for f in FILES:
        assert "(%s)" % f in index, "INDEX.md が %s を載せていない" % f
    readme = open(os.path.join(ROOT, "docs", "README.md"), encoding="utf-8").read()
    assert "literature/INDEX.md" in readme, "docs/README.md(全体地図)から literature/INDEX.md へ辿れない"


@pytest.mark.parametrize("name", FILES)
def test_op_links_point_at_real_notes(name):
    md = _read(name)
    links = re.findall(r"\]\(\.\./ops/([^)]+\.md)\)", md)
    assert links, "%s: op ノートへのリンクが 1 本も無い(知識が op に落ちていない)" % name
    missing = sorted({p for p in links if not os.path.isfile(os.path.join(ROOT, "docs", "ops", p))})
    assert not missing, "%s: 実在しないノートを指す op リンク %d 本: %s" % (name, len(missing), missing[:5])


@pytest.mark.parametrize("name", FILES)
def test_every_top_cluster_has_op_candidates(name):
    md = _read(name)
    tops = [m.group(1) for m in re.finditer(r"^## (.+)$", md, re.M) if m.group(1) not in ("目次", "op → クラスタ(逆引き)")]
    assert len(tops) >= 4, "%s: 上位クラスタが %d しか無い" % (name, len(tops))
    body = md.split("## 目次", 1)[-1]
    n_sections = body.count("**使う op**(")
    assert n_sections == len(tops), "%s: 「使う op」節 %d ≠ 上位クラスタ %d" % (name, n_sections, len(tops))
    # 「op に落ちていない」クラスタは INDEX の列で数えるので、ここでは節の存在だけを見る(隠さない、が門)


@pytest.mark.parametrize("name", FILES + ["INDEX.md"])
def test_no_abstracts_and_no_local_paths(name):
    md = _read(name)
    assert "## Abstract" not in md, "%s: 抄録を写している" % name
    bad = [ln for ln in md.splitlines()
           if re.search(r"(?<![A-Za-z])[A-Z]:[\\/]|(?<![\w/])/c/|\\\\[A-Za-z0-9_.-]+\\|(?<![\w:/.])/(?:home|Users|tmp|mnt)/", ln)]
    assert not bad, "%s: 手元の絶対パスが公開物に混ざっている: %s" % (name, bad[:3])


def test_oss_landscape_is_drawn_from_its_json():
    """OSS の地図: JSON の行数 = 表の行数、URL は https、検証済みの印が JSON と一致、copyleft の印がライセンス欄と一致。"""
    import json
    path = os.path.join(LIT, "OSS_LANDSCAPE.md")
    data = json.load(open(os.path.join(LIT, "oss_landscape.json"), encoding="utf-8"))
    md = open(path, encoding="utf-8").read()
    rows = [ln for ln in md.splitlines() if ln.startswith("| [")]
    assert len(rows) == len(data) >= 20, "OSS_LANDSCAPE.md の行 %d ≠ oss_landscape.json %d(生成器を回し直すこと)" % (len(rows), len(data))
    urls = re.findall(r"^\| \[[^\]]+\]\(([^)]+)\)", md, re.M)
    assert all(u.startswith(("https://", "http://")) for u in urls), [u for u in urls if not u.startswith("http")][:3]   # gwyddion.net は http
    assert sum(1 for ln in rows if ln.rstrip().endswith("| ✓ |")) == sum(1 for e in data if e.get("verified")), "検証済みの印が JSON と合わない"
    for ln in rows:
        cells = [c.strip() for c in ln.strip("|").split("|")]
        lic = cells[1]
        assert ("⚠copyleft" in lic) == any(k in lic.upper() for k in ("GPL", "AGPL", "LGPL", "EUPL", "CECILL")), ln[:80]


def test_index_counts_match_files():
    index = _read("INDEX.md")
    for f in FILES:
        md = _read(f)
        clusters = int(re.search(r"\*\*(\d+) クラスタ\*\*", md).group(1))
        leaves = md.count("\n### ")
        row = next((ln for ln in index.splitlines() if "(%s)" % f in ln), "")
        cells = [c.strip() for c in row.strip("|").split("|")]
        # 列: 文献層 | 論文 | クラスタ | 上位 | 葉 | 代表論文 | op リンク | 挙がった op | op に落ちていない | 構築日
        assert len(cells) >= 10, "INDEX.md の行が壊れている: %r" % row
        assert int(cells[2]) == clusters and int(cells[4]) == leaves, \
            "%s: INDEX の クラスタ/葉 (%s/%s) ≠ 本文 (%d/%d)" % (f, cells[2], cells[4], clusters, leaves)
        uncovered = md.count("**op に落ちていない**")
        assert cells[8].startswith("%d / " % uncovered), "%s: INDEX の「op に落ちていない」%s ≠ 本文 %d" % (f, cells[8], uncovered)
