"""fullseye — evolvable HALCON-parity image-operator library + pipeline designer.

Public package facade. Import this from any project::

    import fullseye
    out = fullseye.apply(frame, "gauss_filter")        # numpy in, numpy out
    seg = fullseye.run_pipeline(frame, ["gaussian", "sobel_amp", "otsu"])

The engine modules (``ops``, ``backends*``, ``evolve``, ``scale`` ...) live one
directory up as flat modules for historical reasons; this facade puts that
directory on ``sys.path`` and re-exports the stable API defined in ``api.py``.
Everything here works on numpy arrays with no file I/O (see :func:`apply`).
"""
from __future__ import annotations

import os
import sys
import warnings

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

# The extended backends run a wavelet transform at build() time which emits a
# benign pywt boundary UserWarning; keep the consumer's import clean.
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    from api import (  # noqa: E402,F401
        apply, run_pipeline, find_op, list_ops, op_names, categories,
        read_image, write_image, RT, REGISTRY, __version__, version,
        stereo, disparity_map, disparity_subpixel, lr_consistency,
        depth_from_disparity, reproject_to_points,
        census_transform, disparity_census, disparity_sgm,
        speckle_filter, fill_disparity, disparity_confidence,
        terrain, elevation_map, traversability, foothold_score, fill_gaps,
        ground_surface, ground_plane, detect_obstacles,
        fuse_elevation, slope_map, roughness_map, surface_normals,
        step_edges, foothold_candidates,
        locomotion, contact_points, com_from_silhouette, support_polygon,
        com_support_margin, gait_phase,
        occupancy, occupancy_grid_2d, inflate_obstacles, clearance_map,
        line_of_sight, frontier_cells,
        imgio, to_float01, to_uint8, apply_cmap, colorize_depth,
        colorize_disparity, colorize_labels, colorize_height, colorize_flow,
        shaded_relief, overlay_mask, save, load, save_ply, COLORMAPS,
        detect, segment_objects, object_descriptor, nearest_prototype, draw_objects,
        registration, kabsch, icp, point_to_plane_icp, apply_transform,
        pca_align, register, feature_register,
        ppf, ppf_model, surface_match, find_surface_pose,
        pointcloud, estimate_normals, voxel_downsample,
        remove_statistical_outliers, remove_radius_outliers, fpfh,
        pcseg, fit_plane, fit_plane_ransac, fit_sphere_ransac, fit_cylinder_ransac,
        plane_distance, height_above_plane, remove_ground,
        euclidean_clusters, region_growing, aabb, obb, crop_box, crop_sphere,
        farthest_point_sampling, curvature, centroid, principal_axes,
        mesh, read_mesh, read_points, write_mesh, write_points, sample_surface,
        mesh_to_points, voxelize, bounds, recenter, normalize_scale,
        meshio_opt, read_gltf, read_gltf_merged, read_las, read_pcd, formats_available,
        volio, read_volume, write_volume, list_dicom_series, VolumeMeta,
        raster, read_raster, to01, read_depth, read_pfm, write_pfm, save16,
        render3d, render_mesh, look_at, intrinsics_from_fov, auto_view,
        mesh_to_sdf, voxelize_solid, marching_cubes,
        camera, intrinsic_matrix, decompose_intrinsics, projection_matrix,
        project_points, backproject, depth_to_points, normals_from_depth,
        triangulate, reprojection_error, solve_pnp, rodrigues, rotation_log,
        fundamental_matrix, essential_matrix, essential_from_fundamental,
        decompose_essential, recover_pose, epipolar_lines,
        distort_points, undistort_points, stereo_rectify,
        odometry, rgbd_odometry, pnp_odometry, integrate_trajectory,
        umeyama_align, trajectory_error,
        grasp, Grasp, sample_antipodal_grasps, grasps_from_mesh, force_closure,
        ferrari_canny_quality, approach_vector_from_normals, rank_grasps,
        grasp_pose, collision_free,
        meshrepair, is_watertight, is_edge_manifold, boundary_edges, weld_vertices,
        remove_degenerate_faces, orient_consistent, fill_holes, smooth_taubin,
        decimate_qem, convex_hull, inertia_tensor, components,
        volops, vol_frangi, vol_sato, vol_hessian_blobness, vol_distance_transform,
        vol_label, vol_region_props, vol_gradient_magnitude, vol_local_maxima, vol_watershed,
        vol_reduce_domain, vol_bounding_box, vol_crop_domain, vol_uncrop,
        vol_boundary, vol_boundary_points, vol_tiled_map,
        volregion, VolRLE, vol_rle_encode, vol_rle_decode, vol_rle_volume,
        vol_rle_bbox, vol_rle_centroid, vol_rle_union, vol_rle_intersect,
        vol_rle_difference, vol_rle_components,
        volgray, vol_window_level, vol_equalize, vol_gamma, vol_stretch,
        volxform, vol_resize, vol_rotate, vol_affine,
        volprobe, vol_profile_line, vol_edge_probe, vol_wall_thickness,
        volfreq, vol_fft_lowpass, vol_fft_highpass, vol_fft_bandpass,
        volrestore, vol_gaussian_psf, vol_richardson_lucy,
        handpose, hand_landmarks, finger_flexions, hand_skeleton_edges, draw_hand_landmarks,
        complexops, cx_fft, cx_ifft, cx_magnitude, cx_phase, cx_real, cx_imag,
        cx_log_magnitude, cx_from_mag_phase, phase_unwrap, cx_wiener_deconvolve,
        cx_apply_transfer_function, cx_bandpass,
        specops, BandMeta, read_envi, write_envi, spec_band, spec_rgb_composite,
        spec_nearest_band, spec_band_ratio, spec_index, spec_angle_mapper, spec_pca,
        spec_mnf, spec_unmix, spec_endmembers_ppi, spec_continuum_removal,
        spec_pansharpen, spec_decorrelation_stretch, spec_fuse,
        deformreg, warp_by_field, demons_register, field_magnitude, residual_ssd,
        videops, temporal_mean, temporal_median, temporal_std, temporal_max,
        temporal_min, frame_difference, background_subtraction, temporal_gradient,
        motion_energy, moving_average, spatiotemporal_gaussian, spatiotemporal_sobel,
        per_frame, flicker_reduce, optical_flow_sequence,
        pose, pose_descriptor, skeleton_nodes, principal_axis,
        flow, optical_flow_lk, optical_flow_hs, warp_by_flow,
        flow_magnitude, flow_angle, track_points,
        motion, frame_motion_energy, dominant_motion, flow_from_model,
        residual_motion, motion_segments, motion_energy_series, detect_events,
        sceneflow, flow_divergence, flow_curl, focus_of_expansion, time_to_contact,
        looming, ego_translation_from_flow, scene_flow,
        features, harris_corners, fast_corners, describe_patches,
        match_descriptors, match_keypoints,
        events, simulate_events, event_count, event_image, event_rate,
        event_rate_map, time_surface, warp_frame, contrast_maximization,
        video, read_frames, iter_frames, frame_pairs, write_video, probe,
        recipes, recipe, measure, line_profile, distance, angle,
        fit_line, fit_circle, fit_ellipse, fit_rectangle2,
        fit_line3, fit_plane3, fit_sphere3, fit_circle3,
        smallest_box3, smallest_box3_axis, fit_box3, smallest_sphere3, inner_box3,
        measure3d, regionprops3d, ops3d, pipeline3d,
        algo, algo_ops, algo_categories, find_algo, run_algo,
        algo_to_python, algo_to_c, algo_difftest,
        synth, learn_features, synthesize_like, match_histogram,
        radial_power_spectrum, feature_distance, patch_novelty, pyramid_stat_distance,
        funct1d, smooth_funct_1d_gauss, smooth_funct_1d_mean,
        derivate_funct_1d, integrate_funct_1d,
        zero_crossings_funct_1d, local_min_max_funct_1d,
        funct_1d_to_pairs, abs_funct_1d, negate_funct_1d, scale_y_funct_1d,
        compose_funct_1d, num_points_funct_1d, distance_funct_1d,
        sample_funct_1d, get_pair_funct_1d, invert_funct_1d,
        transform_funct_1d, x_range_funct_1d, y_range_funct_1d,
        get_y_value_funct_1d, create_funct_1d_array, create_funct_1d_pairs,
        match_funct_1d_trans,
        mathops, mat_solve, mat_lstsq, mat_svd, mat_eigh, mat_pinv, mat_cond,
        stat_describe, stat_histogram, stat_covariance, stat_correlation,
        stat_zscore,
        interp_linear, interp_cubic, poly_fit, poly_eval, poly_roots,
        cplx_contour_circle, cplx_poly_eval, cplx_contour_integral,
        cplx_winding_number, cplx_cauchy_value, cplx_argument_principle,
        cplx_laurent_coeffs, cplx_joukowski, cplx_mobius, cplx_cr_residual,
        visiondesign, system_geometry, resolving_power, system_feasibility,
        image_formation, detectability_limit,
        defectgen, defect_scratch, defect_pits, defect_crack, defect_blob,
        surface_texture, composite_defect, defect_stats,
        visionlab, VisionSystem, render_part, inspection_sweep, detection_report,
        lightfield, lf_synthesize, lf_from_mla, lf_to_mla, lf_stats,
        lf_subaperture, lf_center_view, lf_views, lf_epi,
        lf_refocus, lf_focal_stack, lf_aperture_mask, lf_synthetic_aperture,
        lf_depth_from_focus, lf_epi_slope, lf_disparity_to_depth,
        lf_all_in_focus, lf_plenoptic_design,
        photoncount, photon_sample, photon_statistics, photon_uncertainty,
        anscombe_transform, anscombe_inverse,
        spad_deadtime_apply, spad_deadtime_correct, tcspc_coates_correct,
        tcspc_simulate, tcspc_irf_convolve, tcspc_background_subtract,
        tcspc_stats, dtof_depth, dtof_cube_simulate, dtof_cube_depth,
        lifetime_fit, lifetime_phasor,
        specularity, motionmag, pose_quat, quatimage, rangedoppler,
        acoustics, interferometry,
        gfx2d, alpha_composite, alpha_composite_premul, blend_mode, bloom,
        chromatic_aberration, color_grade, color_lut, dither, film_grain,
        layer_stack, light_mask, linear_to_srgb, nine_slice, normal_map_decode,
        normal_map_shade, palette_quantize, parallax_layers, particle_emit,
        particle_render, particle_step, premultiply, radial_light,
        shadow_cast_2d, sprite_blit, sprite_sheet_slice, sprite_synthesize,
        sprite_transform, srgb_to_linear, tilemap_render, unpremultiply,
        vignette, viewport, BLEND_MODES,
        cadmap, cad_pixel_to_surface, cad_surface_to_pixel,
        cad_defect_to_cad, cad_visible_faces,
        palette, semantic_palette, role_color, role_rgb8, diverging_lut,
        assert_not_red_green_pair, ROLES, ROLE_MARKERS, SCHEMES,
        annotate, opsannotate, measure_text, text_box, arrow, leader_line,
        label_points, crosshair, legend_box, color_bar, scale_bar,
        axes_transform, data_to_pixel, nice_ticks, axes_frame, grid_lines,
        ticks, plot_series, overlay_labels, zoom_inset, compare_frame,
        panel_grid, rounded_rect, filled_polygon, arc, ellipse,
        drawlist, DrawList, DrawListError, diff_command_lists, format_diff,
        flush_buffer, default_text_metrics, COMMAND_SPECS, TEXT_ADVANCE_RATIO,
        drawstyle, DrawStyle, draw_style, current_style, set_color,
        set_line_width, set_line_style, set_draw, resolve_pattern,
        resolve_color, LINE_STYLES, DRAW_MODES,
        imagedraw, draw_line, draw_polyline, draw_circle, draw_markers,
        draw_contour, new_canvas,
        tomography, projection_angles, sinogram_design, ellipse_phantom,
        ellipse_sinogram, radon_transform, backproject_sinogram,
        filtered_backprojection, sart_reconstruct, beam_hardening_apply,
        beam_hardening_correct, ring_artifact_apply, ring_artifact_remove,
        metal_trace_interpolate, sinogram_center_of_rotation,
        sinogram_center_shift, radon_volume, fbp_volume,
        volcolor, vol_colorize_labels, vol_label_color_flicker,
        vol_label_legend, vol_label_mpr_rgb, vol_label_overlay,
        vol_label_palette, vol_label_shape_stats, vol_label_slice_rgb,
        vol_label_volume_render, vol_labels_to_meshes, vol_select_labels,
        chromatic_confocal_height, chromatic_confocal_simulate,
        csi_contrast_map, csi_design, csi_envelope, csi_height_map,
        csi_peak_position, csi_signal_simulate, csi_stack_simulate,
        angular_resample, apply_weighting, bearing_defect_frequencies,
        cepstrum, coherence, envelope_spectrum, equivalent_level, istft,
        octave_bands, octave_spectrum, order_spectrum, percentile_level,
        spectral_kurtosis, stft, stft_cola_check,
        synthesize_bearing_signal, synthesize_speed_ramp,
        transfer_function, weighting_response,
        beamform_delay_sum, beamform_doa, fmcw_beat_simulate,
        fmcw_design, fmcw_range_profile, fmcw_window_apply,
        range_doppler_map, range_doppler_peaks,
        iqft2, monogenic_amplitude, monogenic_orientation,
        monogenic_phase, monogenic_signal, qft2, quat_color_filter,
        quat_color_rotate, quat_conjugate_image, quat_correlate,
        quat_image_multiply, quat_norm, quat_normalize_image,
        quaternion_to_rgb, rgb_to_quaternion, riesz_displacement,
        riesz_displacement_series, riesz_motion_magnify, riesz_transform,
        axis_angle_to_quat, convert_point_3d_cart_to_spher,
        convert_point_3d_spher_to_cart, convert_pose_type, create_pose,
        dual_quat_compose, dual_quat_conjugate, dual_quat_interpolate,
        dual_quat_normalize, dual_quat_to_pose, dual_quat_to_screw,
        dual_quat_trans_point_3d, get_pose_type, hom_mat3d_to_pose_local,
        pose_average, pose_compose, pose_invert, pose_to_dual_quat,
        pose_to_hom_mat3d_local, pose_to_quat, quat_compose,
        quat_conjugate, quat_interpolate, quat_normalize,
        quat_rotate_point_3d, quat_to_hom_mat3d, quat_to_pose,
        screw_to_dual_quat,
        band_snr, complex_steerable_decompose,
        complex_steerable_reconstruct, displacement_series,
        motion_magnify, phase_displacement, synthesize_translation,
        temporal_band_power, temporal_bandpass,
        specular_diffuse_split, specular_free_transform,
        specular_coefficient_map, illuminant_from_dichromatic_planes,
        brdf_blinn_phong, brdf_microfacet, dichromatic_render,
        photometric_stereo_robust, photometric_residual,
        polarization_render, polarization_separate,
        polarization_dolp_map, polarization_stokes,
        optics, thin_lens, abcd_matrix, abcd_trace, depth_of_field,
        relative_illumination,
        airy_pattern, angular_spectrum_propagate, fraunhofer_pattern,
        gaussian_beam,
        psf_to_mtf, mtf_diffraction, wavefront_stats,
        jones_element, jones_apply, stokes_from_jones,
        mueller_element, mueller_apply, stokes_analyze,
    )
    from engine import FullseyeEngine, diagnose_stages  # noqa: E402,F401  (pipeline runtime)
    import graphengine  # noqa: E402,F401  (DAG pipeline runtime)
    from graphengine import FullseyeGraph  # noqa: E402,F401
    from acquire import (  # noqa: E402,F401  (image acquisition: cameras / framegrabbers)
        Camera, list_cameras, open_framegrabber, grab_image, close_framegrabber,
    )
    from comm import (  # noqa: E402,F401  (communication transports / industrial protocols)
        open_channel, protocols, Channel,
        TcpChannel, UdpChannel, HttpChannel, ModbusTcpChannel, ModbusTcpServer,
    )
    from device import DigitalIO, pulse, signal_result, signal_verdict, wait_input  # noqa: E402,F401  (device control)
    import dsp  # noqa: E402,F401  (1-D signal / acoustic / vibration)
    from dsp import (  # noqa: E402,F401  (1-D signal / acoustic / vibration — beyond images)
        read_wav, write_wav, read_audio, spectrum, spectrogram,
        lowpass, highpass, bandpass, envelope, rms, find_peaks, signal_features,
        resample, zero_crossing_rate,
    )
    # 統一視覚 I/F(要件 F1/F2/F3): 600 の HALCON facade op を単一 registry + 章別名前空間で公開。
    # 例: fullseye.vision.contour.gen_circle_contour_xld(row=50, col=50, radius=10)
    #     fullseye.vision_ops.find("stereo") / .describe("camera_calibration")
    import unified as vision  # noqa: E402,F401
    vision_ops = vision.ops   # 単一 registry(list/find/describe/stats)
    # F5 合成: op を段組み/文のように繋ぐ(fs.Image(arr).median().sobel_amp() / fs.pipeline(...))
    Image = vision.Image          # noqa: F401  画像チェーン(§7)
    Pipeline = vision.Pipeline    # noqa: F401  汎用パイプライン
    pipeline = vision.pipeline    # noqa: F401  可変長ビルダ


def capabilities() -> dict:
    """What this install can connect to and drive, across all three connectivity
    families: ``{"comm": [...], "acquire": [...], "device": [...]}``. Each entry
    reports ``kind`` (native / optional / scaffold), whether it is ``available``
    here, and the ``pip`` package that unlocks it. The comprehensive, honest menu
    of protocols (23), image sources (9) and device drivers (12)."""
    import comm
    import acquire
    import device
    return {"comm": comm.capabilities(),
            "acquire": acquire.capabilities(),
            "device": device.capabilities()}

__all__ = [
    "apply", "run_pipeline", "find_op", "list_ops", "op_names", "categories",
    "read_image", "write_image", "RT", "REGISTRY", "__version__", "version",
    "stereo", "disparity_map", "disparity_subpixel", "lr_consistency",
    "depth_from_disparity", "reproject_to_points",
    "census_transform", "disparity_census", "disparity_sgm",
    "speckle_filter", "fill_disparity", "disparity_confidence",
    "terrain", "elevation_map", "traversability", "foothold_score", "fill_gaps",
    "ground_surface", "ground_plane", "detect_obstacles",
    "fuse_elevation", "slope_map", "roughness_map", "surface_normals",
    "step_edges", "foothold_candidates",
    "locomotion", "contact_points", "com_from_silhouette", "support_polygon",
    "com_support_margin", "gait_phase",
    "occupancy", "occupancy_grid_2d", "inflate_obstacles", "clearance_map",
    "line_of_sight", "frontier_cells",
    "imgio", "to_float01", "to_uint8", "apply_cmap", "colorize_depth",
    "colorize_disparity", "colorize_labels", "colorize_height", "colorize_flow",
    "shaded_relief", "overlay_mask", "save", "load", "save_ply", "COLORMAPS",
    "detect", "segment_objects", "object_descriptor", "nearest_prototype", "draw_objects",
    "registration", "kabsch", "icp", "point_to_plane_icp", "apply_transform",
    "pca_align", "register", "feature_register",
    "ppf", "ppf_model", "surface_match", "find_surface_pose",
    "pointcloud", "estimate_normals", "voxel_downsample",
    "remove_statistical_outliers", "remove_radius_outliers", "fpfh",
    "pcseg", "fit_plane", "fit_plane_ransac", "fit_sphere_ransac", "fit_cylinder_ransac",
    "plane_distance", "height_above_plane", "remove_ground",
    "euclidean_clusters", "region_growing", "aabb", "obb", "crop_box", "crop_sphere",
    "farthest_point_sampling", "curvature", "centroid", "principal_axes",
    "mesh", "read_mesh", "read_points", "write_mesh", "write_points", "sample_surface",
    "mesh_to_points", "voxelize", "bounds", "recenter", "normalize_scale",
    "meshio_opt", "read_gltf", "read_gltf_merged", "read_las", "read_pcd", "formats_available",
    "volio", "read_volume", "write_volume", "list_dicom_series", "VolumeMeta",
    "raster", "read_raster", "to01", "read_depth", "read_pfm", "write_pfm", "save16",
    "render3d", "render_mesh", "look_at", "intrinsics_from_fov", "auto_view",
    "mesh_to_sdf", "voxelize_solid", "marching_cubes",
    "camera", "intrinsic_matrix", "decompose_intrinsics", "projection_matrix",
    "project_points", "backproject", "depth_to_points", "normals_from_depth",
    "triangulate", "reprojection_error", "solve_pnp", "rodrigues", "rotation_log",
    "fundamental_matrix", "essential_matrix", "essential_from_fundamental",
    "decompose_essential", "recover_pose", "epipolar_lines",
    "distort_points", "undistort_points", "stereo_rectify",
    "odometry", "rgbd_odometry", "pnp_odometry", "integrate_trajectory",
    "umeyama_align", "trajectory_error",
    "grasp", "Grasp", "sample_antipodal_grasps", "grasps_from_mesh", "force_closure",
    "ferrari_canny_quality", "approach_vector_from_normals", "rank_grasps",
    "grasp_pose", "collision_free",
    "meshrepair", "is_watertight", "is_edge_manifold", "boundary_edges", "weld_vertices",
    "remove_degenerate_faces", "orient_consistent", "fill_holes", "smooth_taubin",
    "decimate_qem", "convex_hull", "inertia_tensor", "components",
    "volops", "vol_frangi", "vol_sato", "vol_hessian_blobness", "vol_distance_transform",
    "vol_label", "vol_region_props", "vol_gradient_magnitude", "vol_local_maxima", "vol_watershed",
    "vol_reduce_domain", "vol_bounding_box", "vol_crop_domain", "vol_uncrop",
    "vol_boundary", "vol_boundary_points", "vol_tiled_map",
    "volregion", "VolRLE", "vol_rle_encode", "vol_rle_decode", "vol_rle_volume",
    "vol_rle_bbox", "vol_rle_centroid", "vol_rle_union", "vol_rle_intersect",
    "vol_rle_difference", "vol_rle_components",
    "volgray", "vol_window_level", "vol_equalize", "vol_gamma", "vol_stretch",
    "volxform", "vol_resize", "vol_rotate", "vol_affine",
    "volprobe", "vol_profile_line", "vol_edge_probe", "vol_wall_thickness",
    "volfreq", "vol_fft_lowpass", "vol_fft_highpass", "vol_fft_bandpass",
    "volrestore", "vol_gaussian_psf", "vol_richardson_lucy",
    "handpose", "hand_landmarks", "finger_flexions", "hand_skeleton_edges", "draw_hand_landmarks",
    "complexops", "cx_fft", "cx_ifft", "cx_magnitude", "cx_phase", "cx_real", "cx_imag",
    "cx_log_magnitude", "cx_from_mag_phase", "phase_unwrap", "cx_wiener_deconvolve",
    "cx_apply_transfer_function", "cx_bandpass",
    "specops", "BandMeta", "read_envi", "write_envi", "spec_band", "spec_rgb_composite",
    "spec_nearest_band", "spec_band_ratio", "spec_index", "spec_angle_mapper", "spec_pca",
    "spec_mnf", "spec_unmix", "spec_endmembers_ppi", "spec_continuum_removal",
    "spec_pansharpen", "spec_decorrelation_stretch", "spec_fuse",
    "deformreg", "warp_by_field", "demons_register", "field_magnitude", "residual_ssd",
    "videops", "temporal_mean", "temporal_median", "temporal_std", "temporal_max",
    "temporal_min", "frame_difference", "background_subtraction", "temporal_gradient",
    "motion_energy", "moving_average", "spatiotemporal_gaussian", "spatiotemporal_sobel",
    "per_frame", "flicker_reduce", "optical_flow_sequence",
    "pose", "pose_descriptor", "skeleton_nodes", "principal_axis",
    "flow", "optical_flow_lk", "optical_flow_hs", "warp_by_flow",
    "flow_magnitude", "flow_angle", "track_points",
    "motion", "frame_motion_energy", "dominant_motion", "flow_from_model",
    "residual_motion", "motion_segments", "motion_energy_series", "detect_events",
    "sceneflow", "flow_divergence", "flow_curl", "focus_of_expansion", "time_to_contact",
    "looming", "ego_translation_from_flow", "scene_flow",
    "features", "harris_corners", "fast_corners", "describe_patches",
    "match_descriptors", "match_keypoints",
    "events", "simulate_events", "event_count", "event_image", "event_rate",
    "event_rate_map", "time_surface", "warp_frame", "contrast_maximization",
    "video", "read_frames", "iter_frames", "frame_pairs", "write_video", "probe",
    "recipes", "recipe", "measure", "line_profile", "distance", "angle",
    "fit_line", "fit_circle", "fit_ellipse", "fit_rectangle2",
    "fit_line3", "fit_plane3", "fit_sphere3", "fit_circle3",
    "smallest_box3", "smallest_box3_axis", "fit_box3", "smallest_sphere3", "inner_box3",
    "measure3d", "regionprops3d", "ops3d", "pipeline3d",
    "FullseyeEngine", "diagnose_stages", "graphengine", "FullseyeGraph",
    "Camera", "list_cameras", "open_framegrabber", "grab_image", "close_framegrabber",
    "open_channel", "protocols", "capabilities", "Channel",
    "TcpChannel", "UdpChannel", "HttpChannel", "ModbusTcpChannel", "ModbusTcpServer",
    "DigitalIO", "pulse", "signal_result", "signal_verdict", "wait_input",
    "read_wav", "write_wav", "read_audio", "spectrum", "spectrogram",
    "lowpass", "highpass", "bandpass", "envelope", "rms", "find_peaks", "signal_features",
    "algo", "algo_ops", "algo_categories", "find_algo", "run_algo",
    "algo_to_python", "algo_to_c", "algo_difftest",
    "synth", "learn_features", "synthesize_like", "match_histogram",
    "radial_power_spectrum", "feature_distance", "patch_novelty", "pyramid_stat_distance",
    "funct1d", "smooth_funct_1d_gauss", "smooth_funct_1d_mean",
    "derivate_funct_1d", "integrate_funct_1d",
    "zero_crossings_funct_1d", "local_min_max_funct_1d",
    "funct_1d_to_pairs", "abs_funct_1d", "negate_funct_1d", "scale_y_funct_1d",
    "compose_funct_1d", "num_points_funct_1d", "distance_funct_1d",
    "sample_funct_1d", "get_pair_funct_1d", "invert_funct_1d",
    "transform_funct_1d", "x_range_funct_1d", "y_range_funct_1d",
    "get_y_value_funct_1d", "create_funct_1d_array", "create_funct_1d_pairs",
    "match_funct_1d_trans",
    "mathops", "mat_solve", "mat_lstsq", "mat_svd", "mat_eigh", "mat_pinv", "mat_cond",
    "stat_describe", "stat_histogram", "stat_covariance", "stat_correlation",
    "stat_zscore",
    "interp_linear", "interp_cubic", "poly_fit", "poly_eval", "poly_roots",
    "cplx_contour_circle", "cplx_poly_eval", "cplx_contour_integral",
    "cplx_winding_number", "cplx_cauchy_value", "cplx_argument_principle",
    "cplx_laurent_coeffs", "cplx_joukowski", "cplx_mobius", "cplx_cr_residual",
    "visiondesign", "system_geometry", "resolving_power", "system_feasibility",
    "image_formation", "detectability_limit",
    "defectgen", "defect_scratch", "defect_pits", "defect_crack", "defect_blob",
    "surface_texture", "composite_defect", "defect_stats",
    "visionlab", "VisionSystem", "render_part", "inspection_sweep",
    "detection_report",
    "lightfield", "lf_synthesize", "lf_from_mla", "lf_to_mla", "lf_stats",
    "lf_subaperture", "lf_center_view", "lf_views", "lf_epi",
    "lf_refocus", "lf_focal_stack", "lf_aperture_mask", "lf_synthetic_aperture",
    "lf_depth_from_focus", "lf_epi_slope", "lf_disparity_to_depth",
    "lf_all_in_focus", "lf_plenoptic_design",
    "photoncount", "photon_sample", "photon_statistics", "photon_uncertainty",
    "anscombe_transform", "anscombe_inverse",
    "spad_deadtime_apply", "spad_deadtime_correct", "tcspc_coates_correct",
    "tcspc_simulate", "tcspc_irf_convolve", "tcspc_background_subtract",
    "tcspc_stats", "dtof_depth", "dtof_cube_simulate", "dtof_cube_depth",
    "lifetime_fit", "lifetime_phasor",
    # dsp の 12 名は上流で既に export 済み。ここで足すのは module 参照と
    # 漏れていた 2 つだけ(2026-09-01: 全部足して重複させた回帰)
    "dsp", "resample", "zero_crossing_rate",
    "specularity", "motionmag", "pose_quat", "quatimage", "rangedoppler",
    "acoustics", "interferometry",
    "cadmap", "cad_pixel_to_surface", "cad_surface_to_pixel",
    "cad_defect_to_cad", "cad_visible_faces",
    "palette", "semantic_palette", "role_color", "role_rgb8", "diverging_lut", "assert_not_red_green_pair", "ROLES", "ROLE_MARKERS", "SCHEMES",
    "annotate", "opsannotate", "measure_text", "text_box", "arrow", "leader_line",
    "label_points", "crosshair", "legend_box", "color_bar", "scale_bar",
    "axes_transform", "data_to_pixel", "nice_ticks", "axes_frame", "grid_lines",
    "ticks", "plot_series", "overlay_labels", "zoom_inset", "compare_frame",
    "panel_grid", "rounded_rect", "filled_polygon", "arc", "ellipse",
    "drawlist", "DrawList", "DrawListError", "diff_command_lists", "format_diff", "flush_buffer", "default_text_metrics", "COMMAND_SPECS", "TEXT_ADVANCE_RATIO",
    "drawstyle", "DrawStyle", "draw_style", "current_style", "set_color", "set_line_width", "set_line_style", "set_draw", "resolve_pattern", "resolve_color", "LINE_STYLES", "DRAW_MODES",
    "imagedraw", "draw_line", "draw_polyline", "draw_circle", "draw_markers", "draw_contour", "new_canvas",
    "tomography", "projection_angles", "sinogram_design", "ellipse_phantom",
    "ellipse_sinogram", "radon_transform", "backproject_sinogram",
    "filtered_backprojection", "sart_reconstruct", "beam_hardening_apply",
    "beam_hardening_correct", "ring_artifact_apply", "ring_artifact_remove",
    "metal_trace_interpolate", "sinogram_center_of_rotation",
    "sinogram_center_shift", "radon_volume", "fbp_volume",
    "volcolor", "vol_colorize_labels", "vol_label_color_flicker",
    "vol_label_legend", "vol_label_mpr_rgb", "vol_label_overlay",
    "vol_label_palette", "vol_label_shape_stats", "vol_label_slice_rgb",
    "vol_label_volume_render", "vol_labels_to_meshes", "vol_select_labels",
    "chromatic_confocal_height", "chromatic_confocal_simulate",
    "csi_contrast_map", "csi_design", "csi_envelope", "csi_height_map",
    "csi_peak_position", "csi_signal_simulate", "csi_stack_simulate",
    "angular_resample", "apply_weighting", "bearing_defect_frequencies",
    "cepstrum", "coherence", "envelope_spectrum", "equivalent_level",
    "istft", "octave_bands", "octave_spectrum", "order_spectrum",
    "percentile_level", "spectral_kurtosis", "stft", "stft_cola_check",
    "synthesize_bearing_signal", "synthesize_speed_ramp",
    "transfer_function", "weighting_response",
    "beamform_delay_sum", "beamform_doa", "fmcw_beat_simulate",
    "fmcw_design", "fmcw_range_profile", "fmcw_window_apply",
    "range_doppler_map", "range_doppler_peaks",
    "iqft2", "monogenic_amplitude", "monogenic_orientation",
    "monogenic_phase", "monogenic_signal", "qft2", "quat_color_filter",
    "quat_color_rotate", "quat_conjugate_image", "quat_correlate",
    "quat_image_multiply", "quat_norm", "quat_normalize_image",
    "quaternion_to_rgb", "rgb_to_quaternion", "riesz_displacement",
    "riesz_displacement_series", "riesz_motion_magnify",
    "riesz_transform",
    "axis_angle_to_quat", "convert_point_3d_cart_to_spher",
    "convert_point_3d_spher_to_cart", "convert_pose_type", "create_pose",
    "dual_quat_compose", "dual_quat_conjugate", "dual_quat_interpolate",
    "dual_quat_normalize", "dual_quat_to_pose", "dual_quat_to_screw",
    "dual_quat_trans_point_3d", "get_pose_type",
    "hom_mat3d_to_pose_local", "pose_average", "pose_compose",
    "pose_invert", "pose_to_dual_quat", "pose_to_hom_mat3d_local",
    "pose_to_quat", "quat_compose", "quat_conjugate", "quat_interpolate",
    "quat_normalize", "quat_rotate_point_3d", "quat_to_hom_mat3d",
    "quat_to_pose", "screw_to_dual_quat",
    "band_snr", "complex_steerable_decompose",
    "complex_steerable_reconstruct", "displacement_series",
    "motion_magnify", "phase_displacement", "synthesize_translation",
    "temporal_band_power", "temporal_bandpass",
    "specular_diffuse_split", "specular_free_transform",
    "specular_coefficient_map", "illuminant_from_dichromatic_planes",
    "brdf_blinn_phong", "brdf_microfacet", "dichromatic_render",
    "photometric_stereo_robust", "photometric_residual",
    "polarization_render", "polarization_separate",
    "polarization_dolp_map", "polarization_stokes",
    "optics", "thin_lens", "abcd_matrix", "abcd_trace", "depth_of_field",
    "relative_illumination",
    "airy_pattern", "angular_spectrum_propagate", "fraunhofer_pattern",
    "gaussian_beam",
    "psf_to_mtf", "mtf_diffraction", "wavefront_stats",
    "jones_element", "jones_apply", "stokes_from_jones",
    "mueller_element", "mueller_apply", "stokes_analyze",
    "vision", "vision_ops", "Image", "Pipeline", "pipeline",
]
