# -*- coding: utf-8 -*-
"""build_exhibits — 展示(exhibit)ソースから記事の「紙面の科学館」章を組み立てる。

単一真実源は ``docs/articles/exhibits/`` で、記事本文はその生成物である。
展示ウィングを増やすときにやることは 3 つだけ:

1. ``docs/articles/exhibits/<id>.ja.md`` と ``<id>.en.md`` を置く
   (``<id>.md`` だけでも可 — その場合は ja として扱い、en は ja を流用せず「未訳」で落とす)。
2. ``docs/articles/exhibits/wings.json`` の ``wings`` に ``{"id", "order", "title"}`` を 1 行足す。
3. ``py -3.11 tools/build_exhibits.py`` を走らせる。

章見出しの展示点数は**キャプション行を数えて自動で埋まる**ので、手で数えない。
記事側は次のマーカーで囲まれた範囲だけが差し替わる::

    <!-- EXHIBITS:BEGIN (generated by tools/build_exhibits.py — do not edit by hand) -->
    ...
    <!-- EXHIBITS:END -->

``--check`` は書き込まずに差分の有無だけを返す(exit 1 = 要再生成)。
``tests/test_exhibits.py`` がこれを CI で強制するので、ソースだけ直して本文を
直し忘れる、あるいはその逆、という乖離が起きない。

検査は fail-closed で、次のいずれかがあれば生成せずに落ちる:

* 画像 URL が規約の raw ベースで始まっていない
* 参照している画像が repo に実在しない(**リンク切れの記事を出さない**)
* 画像行の直後にキャプション行が無い(何の op で作った絵か分からない展示を作らない)
* ローカルパス(``C:\\`` など)が混ざっている
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXHIBITS = ROOT / "docs" / "articles" / "exhibits"
ARTICLES = {
    "ja": ROOT / "docs" / "articles" / "fullseye_overview_qiita_ja.md",
    "en": ROOT / "docs" / "articles" / "fullseye_overview_qiita_en.md",
}
BEGIN = "<!-- EXHIBITS:BEGIN (generated by tools/build_exhibits.py — do not edit by hand) -->"
END = "<!-- EXHIBITS:END -->"

_IMG_RE = re.compile(r"!\[[^\]]*\]\((?P<url>[^)\s]+)\)")
# キャプションは「*↑ 」で始まる斜体行。太字の見出しを付けるかは展示ごとの自由。
_CAPTION_RE = re.compile(r"^\*↑ ")
# ドライブレター(C:\ / D:/)と Unix のホーム系。``https://`` の ``s:/`` を拾わないよう、
# 直前が英字のときは除外する。
_LOCAL_PATH_RE = re.compile(r"(?<![A-Za-z])[A-Za-z]:[\\/]|(?<![\w/])/(?:home|Users|tmp)/")


class BuildError(Exception):
    """生成を止める検査失敗。握り潰さず呼び出し側へ返す。"""


def load_manifest() -> dict:
    path = EXHIBITS / "wings.json"
    if not path.exists():
        raise BuildError(f"manifest not found: {path}")
    manifest = json.loads(path.read_text(encoding="utf-8"))
    for key in ("asset_base", "chapter_title", "wings"):
        if key not in manifest:
            raise BuildError(f"wings.json is missing {key!r}")
    seen: set[str] = set()
    for wing in manifest["wings"]:
        wid = wing.get("id")
        if not wid:
            raise BuildError(f"wing entry without an id: {wing!r}")
        if wid in seen:
            raise BuildError(f"duplicate wing id: {wid!r}")
        seen.add(wid)
        if "order" not in wing:
            raise BuildError(f"wing {wid!r} has no order (it decides the exhibit order)")
        for lang in ARTICLES:
            if lang not in wing.get("title", {}):
                raise BuildError(f"wing {wid!r} has no {lang} title")
    return manifest


def wing_source(wid: str, lang: str) -> Path:
    """``<id>.<lang>.md`` を優先し、ja だけは ``<id>.md`` も受ける。

    生成した Agent が言語サフィックス無しで置くことがあるので、ja に限り拾う。
    en は流用しない — 日本語の本文が英語版に紛れ込む方が害が大きい。
    """
    primary = EXHIBITS / f"{wid}.{lang}.md"
    if primary.exists():
        return primary
    if lang == "ja":
        legacy = EXHIBITS / f"{wid}.md"
        if legacy.exists():
            return legacy
    raise BuildError(f"exhibit source not found for wing {wid!r} ({lang}): {primary}")


def check_body(body: str, where: str, asset_base: str, *, require_exhibits: bool = True) -> int:
    """展示本文を検査し、キャプション(= 展示)の数を返す。

    ``require_exhibits=False`` は章の導入用 — 画像 URL とローカルパスの検査だけは
    同じように効かせたいが、導入には展示そのものが無いので数はゼロでよい。
    """
    bad_local = _LOCAL_PATH_RE.search(body)
    if bad_local:
        raise BuildError(f"{where}: a local path leaked into public text: {bad_local.group(0)!r}")

    lines = body.splitlines()
    n_caption = 0
    for i, line in enumerate(lines):
        if _CAPTION_RE.match(line):
            n_caption += 1
        for m in _IMG_RE.finditer(line):
            url = m.group("url")
            if not url.startswith(asset_base):
                raise BuildError(f"{where}: image URL is not under the asset base: {url}")
            rel = url[len(asset_base):]
            local = ROOT / "docs" / "articles" / "assets" / rel
            if not local.exists():
                raise BuildError(f"{where}: referenced asset does not exist: {local}")
        if _IMG_RE.search(line) and not line.lstrip().startswith("<!--"):
            # 画像の後ろにキャプションが来ることを確かめる(空行 1 つは挟んでよい)
            tail = [t for t in lines[i + 1: i + 4] if t.strip()]
            if not tail or not _CAPTION_RE.match(tail[0]):
                raise BuildError(
                    f"{where}: the image on line {i + 1} has no '*↑ **...' caption after it")
    if require_exhibits and n_caption == 0:
        raise BuildError(f"{where}: no exhibits found (a wing with no caption line is empty)")
    return n_caption


def render(manifest: dict, lang: str) -> tuple[str, int]:
    asset_base = manifest["asset_base"]
    wings = sorted(manifest["wings"], key=lambda w: (w["order"], w["id"]))

    intro_path = EXHIBITS / f"_intro.{lang}.md"
    if not intro_path.exists():
        raise BuildError(f"chapter intro not found: {intro_path}")
    intro = intro_path.read_text(encoding="utf-8").strip("\n")

    parts: list[str] = []
    total = 0
    for wing in wings:
        body = wing_source(wing["id"], lang).read_text(encoding="utf-8").strip("\n")
        total += check_body(body, f"{wing['id']}.{lang}", asset_base)
        parts.append(f"### {wing['title'][lang]}\n\n{body}")

    check_body(intro, f"_intro.{lang}", asset_base, require_exhibits=False)

    title = manifest["chapter_title"][lang].format(n=total)
    out = "\n\n".join([BEGIN, f"## {title}", intro, *parts, END])
    return out + "\n", total


def splice(article: Path, block: str) -> bool:
    text = article.read_text(encoding="utf-8")
    start = text.find(BEGIN)
    end = text.find(END)
    if start < 0 or end < 0:
        raise BuildError(f"{article.name}: EXHIBITS markers not found — add them once by hand")
    if end < start:
        raise BuildError(f"{article.name}: EXHIBITS:END appears before EXHIBITS:BEGIN")
    new = text[:start] + block.rstrip("\n") + text[end + len(END):]
    if new == text:
        return False
    article.write_text(new, encoding="utf-8")
    return True


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="書き込まず、再生成が必要なら exit 1")
    args = ap.parse_args(argv)

    try:
        manifest = load_manifest()
        stale: list[str] = []
        for lang, article in ARTICLES.items():
            block, total = render(manifest, lang)
            text = article.read_text(encoding="utf-8")
            start, end = text.find(BEGIN), text.find(END)
            if start < 0 or end < 0:
                raise BuildError(f"{article.name}: EXHIBITS markers not found")
            current = text[start:end + len(END)]
            if current != block.rstrip("\n"):
                stale.append(article.name)
                if not args.check:
                    splice(article, block)
            print(f"{lang}: {len(manifest['wings'])} wings / {total} exhibits"
                  + ("  [stale]" if article.name in stale else "  [up to date]"))
    except BuildError as exc:
        print(f"build_exhibits: {exc}", file=sys.stderr)
        return 2

    if args.check and stale:
        print("stale: " + ", ".join(stale) + "  -> run `py -3.11 tools/build_exhibits.py`",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
