# Copyright (c) 2026 Kazufumi Furuse. Licensed under the Apache License, Version 2.0 (see LICENSE).
"""`★` の付いたコメントを集めて「設計判断集」を 6 言語で生成する。

## なぜ要るか(2026-09-09)

この repo は**読み手向けの層をすでに 6 言語で出している**(op ノート由来の
Studio ヘルプが 10,191 ページ)。日本語だけなのは**保守者向けの層** ——
ソース中のコメントで、実測 100,786 行(全 469,645 行の 21.5 %)ある。

そこを丸ごと 6 言語で併記する形は取らない。約 50 万行に膨らみ、**編集のたびに
6 か所を直す**ことになる。この repo のコメントは「実測 1,135,171 →
1,130,583 バイト」のように**測った値**を書くので、値が変われば必ずどれかが
古びる —— 手で書いた表が現実から遅れる、という今日ずっと潰してきた型の最大版。

代わりに `★` の付いた行だけを対象にする。**3,762 行 / 342 ファイル**(全体の
3.7 %)で、しかも「なぜこうなっているか」という一番価値のある部分。
ソースは日本語のまま単一の正本に保ち、ここから生成物として訳を出す。

## 訳の埋まり方(正直に)

初日から全部は訳せない。未訳の項目は**原文のまま出し、未訳と数える**
(黙って原文に落ちると「訳したつもり」になる)。生成のたびに
`docs/design_notes.json` に `total` / `translated` を書き、
`tests/test_design_notes.py` が **訳の本数が減っていないこと**を見る。
増やすのは歓迎、減らすのは事故。

## 使い方

    py -3.11 tools/gen_design_notes.py            # 生成
    py -3.11 tools/gen_design_notes.py --stats    # 数だけ見る
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, "tools"))

import opdocs as OD  # noqa: E402  (LANGS / LANG_NAMES / _COPYRIGHT を共有)

#: ★対訳表は **op ドキュメントとは別ファイル**にする。`opdocs.T` を使うと
#: 引いた原文が `opdocs.SEEN_STRINGS` に載り、既存の「枠の対訳に穴がある」門が
#: 604 件すべてを穴として数えて CI が落ちる —— あの門は「枠の文言は必ず 5 言語
#: そろえる」ための門で、こちらは「訳せた順に増やす」性質のものだから、
#: **同じ表に混ぜると片方の規律がもう片方を壊す**。
_I18N = os.path.join(_ROOT, "docs", "i18n", "design_notes.json")
_TABLE = None


def _table() -> dict:
    global _TABLE
    if _TABLE is None:
        try:
            with open(_I18N, encoding="utf-8") as f:
                _TABLE = json.load(f).get("strings", {})
        except (OSError, ValueError):
            _TABLE = {}
    return _TABLE


def T(s: str, lang: str) -> str:
    """未訳・未知の言語は**原文のまま**返す(壊れた訳より原文)。"""
    if lang == "ja" or not s:
        return s
    return (_table().get(s) or {}).get(lang) or s

#: 走査から外す。生成物・仮想環境・出力先には正本が無い。
_SKIP_DIRS = ("build/", "out/", ".venv/", ".git/", "studio_assets/")

#: 1 塊 = ★ を含む行から始まり、同じ字下げで続く `#` コメント行の連なり。
#: Sphinx 風の `#:` コメントも拾う。`#` と空白だけを剥ぐと先頭に `:` が
#: 残り、生成物に「: ★…」と出る(実際に出た)。`:` もここで剥ぐ。
_COMMENT = re.compile(r"^(\s*)#:?\s?(.*)$")


def _blocks_in(path: str, rel: str):
    """1 ファイルから ★ コメントの塊を取り出す。"""
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            lines = f.read().splitlines()
    except OSError:
        return []
    out, i = [], 0
    while i < len(lines):
        m = _COMMENT.match(lines[i])
        if not m or "★" not in lines[i]:
            i += 1
            continue
        indent, body = m.group(1), [m.group(2)]
        start = i + 1
        j = i + 1
        while j < len(lines):
            m2 = _COMMENT.match(lines[j])
            if not m2 or m2.group(1) != indent:
                break
            # 次の ★ が来たら別の塊として切る(1 塊 1 主張に保つ)。
            if "★" in lines[j]:
                break
            body.append(m2.group(2))
            j += 1
        text = " ".join(s.strip() for s in body).strip()
        text = re.sub(r"\s+", " ", text)
        if text:
            out.append({"file": rel, "line": start, "text": text})
        i = j
    return out


def collect():
    """repo 全体から ★ 塊を集める(ファイル名・行番号つき)。"""
    blocks = []
    for root, dirs, names in os.walk(_ROOT):
        rel_root = os.path.relpath(root, _ROOT).replace(os.sep, "/")
        if rel_root == ".":
            rel_root = ""
        if any((rel_root + "/").startswith(s) for s in _SKIP_DIRS):
            dirs[:] = []
            continue
        dirs[:] = [d for d in dirs if not d.startswith(".")
                   and d not in ("build", "out", "__pycache__", "studio_assets")]
        for name in sorted(names):
            if not name.endswith(".py"):
                continue
            rel = (rel_root + "/" + name) if rel_root else name
            blocks.extend(_blocks_in(os.path.join(root, name), rel))
    blocks.sort(key=lambda b: (b["file"], b["line"]))
    return blocks


def _translated(text: str, lang: str) -> bool:
    return T(text, lang) != text


def render(blocks, lang: str) -> str:
    n_tr = sum(1 for b in blocks if _translated(b["text"], lang))
    head = [
        "<!-- generated by tools/gen_design_notes.py — do not edit by hand -->",
        T("# Fullseye 設計判断集(ソース中の ★ コメントから生成)", lang),
        "",
        _lang_nav(lang),
        "",
        T("この repo は、なぜそうなっているかを**ソースのコメント**に書いている。"
             "そのうち `★` を付けたものが「効く知見」—— 測って分かったこと、"
             "踏んだ失敗、そう作った理由。ここはそれを機械的に集めた生成物で、"
             "正本はソースの側にある(だから食い違わない)。", lang),
        "",
    ]
    if lang != "ja":
        head += [T("**訳の状況**: {a0} / {a1} 件。未訳の項目は原文(日本語)のまま"
                      "出している —— 黙って原文に落とすと「訳したつもり」になるので、"
                      "訳が無いことは訳が無いと示す。", lang)
                 .format(a0=n_tr, a1=len(blocks)), ""]
    cur = None
    body = []
    for b in blocks:
        if b["file"] != cur:
            cur = b["file"]
            body += ["", "## `%s`" % cur, ""]
        t = T(b["text"], lang)
        # ★印は訳さず `_(ja)_` に固定する。言語ごとに訳すと**機械が数えられない**
        #   —— `tools/i18n_status.py` が「印の無い日本語」を数える道具なので、
        #   印が言語ごとに変わると 593 行が「隠れた日本語」に化ける(実際に化けた)。
        #   `ja` は言語コードで、読み手にも「これは日本語」と伝わる。
        mark = "" if (lang == "ja" or t != b["text"]) else " _(ja)_"
        body.append("- **L%d**%s — %s" % (b["line"], mark, t))
    return "\n".join(head + body + ["", "---", OD._COPYRIGHT, ""])


def _lang_nav(current: str) -> str:
    out = []
    for code in OD.LANGS:
        label = OD.LANG_NAMES.get(code, code)
        name = "DESIGN_NOTES.md" if code == "ja" else "DESIGN_NOTES.%s.md" % code
        out.append("**%s**" % label if code == current else "[%s](./%s)" % (label, name))
    return " · ".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--stats", action="store_true", help="数だけ出して書かない")
    a = ap.parse_args(argv)

    blocks = collect()
    langs = [c for c in OD.LANGS if c != "ja"]
    counts = {c: sum(1 for b in blocks if _translated(b["text"], c)) for c in langs}
    if a.stats:
        print("★ の塊: %d 件 / %d ファイル"
              % (len(blocks), len({b["file"] for b in blocks})))
        for c in langs:
            print("  %s: 訳あり %d 件 (%.1f%%)"
                  % (c, counts[c], 100 * counts[c] / max(len(blocks), 1)))
        return 0

    docs = os.path.join(_ROOT, "docs")
    for lang in OD.LANGS:
        name = "DESIGN_NOTES.md" if lang == "ja" else "DESIGN_NOTES.%s.md" % lang
        with open(os.path.join(docs, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(render(blocks, lang))
    meta = {"total": len(blocks),
            "files": len({b["file"] for b in blocks}),
            "translated": counts}
    with open(os.path.join(docs, "design_notes.json"), "w",
              encoding="utf-8", newline="\n") as f:
        json.dump(meta, f, ensure_ascii=False, indent=1)
        f.write("\n")
    print("design notes: %d 件 / %d ファイル、訳 %s"
          % (meta["total"], meta["files"],
             ", ".join("%s=%d" % (c, counts[c]) for c in langs)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
