#!/usr/bin/env python3
# Copyright (c) 2026 Kazufumi Furuse. Licensed under the Apache License, Version 2.0 (see LICENSE).
"""examples/README.md を `examples2d.EXAMPLES` から生成する。

    py -3.11 tools/gen_examples_readme.py

## なぜ生成にしたか(2026-09-06)

手書きの README には **5 本しか載っていなかった**(実体は 131 本、登録 127 本)。
2026-08-13 に書かれたまま、その後 122 本増えても誰も足さなかった。索引から
「実行可能なエンドツーエンドのサンプルスクリプト集」としてリンクされている
入口がこれでは、**在るものが無いことになる**。

台帳(`examples2d.EXAMPLES`)はギャラリーと門が使っている一次情報なので、
そこから出せば増減が自動で追いつく。ドリフト検査は
`tests/test_docs_index_numbers.py` にある。
"""
from __future__ import annotations

import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _ROOT)

import examples2d as EX  # noqa: E402

#: 見出しに使う task の日本語。載っていない task はそのまま英字で出す。
TASK_JA = {
    "metrology": "計測", "diagnostics": "診断・非破壊検査", "photometry": "測光",
    "imaging_quality": "撮像品質", "optics_sensing": "光学・センシング",
    "optics": "光学", "optics_layout": "光学系の配置", "depth": "深度",
    "flow": "動き", "segmentation": "領域分割", "morphology": "形態",
    "registration": "位置合わせ", "calibration": "校正", "decoding": "読み取り",
    "restoration": "復元", "upscaling": "超解像", "separation": "分離",
    "forensics": "改ざん検出", "terrain": "地形", "tomography": "断層",
    "tomography_3d": "断層(3-D)", "geometry": "幾何", "color": "色",
    "appearance": "見え方", "shape_descriptors": "形の記述",
    "signal_processing": "信号処理", "interpolation": "補間", "math": "数値",
    "drawing": "作図", "morphing": "モーフィング", "ranging": "測距",
    "vibration": "振動", "rectification": "正対化", "consumer": "身近な用途",
    "perception_templates": "知覚のひな型", "family_coverage": "族の網羅",
    "workflow": "ワークフロー",
}

HEAD = """<!-- generated by tools/gen_examples_readme.py — do not hand-edit.
     Source of truth: examples2d.EXAMPLES (the same table the Studio gallery and
     the gates read). Regenerate: py -3.11 tools/gen_examples_readme.py -->
# Examples — 実行できるサンプル {n} 本

外部ファイルに依存しない、**そのままコピーして使える**スクリプト集です。
どれも単体で走ります:

```bash
py -3.11 examples/<name>.py
```

Studio から実行・編集する場合は 2-D Examples ギャラリーに同じものが並びます。
**図を出させたいときだけ** 環境変数を渡してください(未設定なら完全に無処理で、
数値も速度も変わりません):

```bash
FULLSEYE_FIGURE_DIR=out/figs py -3.11 examples/<name>.py
```

うち **{n_poc} 本は PoC シリーズ**(`poc_*.py`)で、**真値を閉形式か合成で厳密に
持ち、ゼロ点(何もしない場合)を必ず併記**します。「うちの手法は 0.9 出ました」
は、何もしなかったときの点数を知るまで意味を持たないからです。
壊れ方は 1 つの指標に畳まず**別々に数え**、原因は**対照群**で分けます。

一覧は `python -c "import examples2d; print(examples2d.names())"` でも取れます。
"""


def build() -> str:
    rows = list(EX.EXAMPLES)
    n_poc = sum(1 for r in rows if r["id"].startswith("poc_"))
    out = [HEAD.format(n=len(rows), n_poc=n_poc)]
    by_task: dict = {}
    for r in rows:
        by_task.setdefault(r["task"], []).append(r)
    for task in sorted(by_task, key=lambda t: (-len(by_task[t]), t)):
        ja = TASK_JA.get(task, task)
        out.append("\n## %s — `%s`(%d 本)\n" % (ja, task, len(by_task[task])))
        out.append("| script | 何を示すか |")
        out.append("|---|---|")
        for r in sorted(by_task[task], key=lambda x: x["id"]):
            summary = " ".join(r["summary"].split())
            out.append("| [`%s.py`](%s.py)<br>%s | %s |"
                       % (r["id"], r["id"], r["name"], summary))
    out.append("")
    return "\n".join(out)


def main() -> int:
    md = build()
    path = os.path.join(_ROOT, "examples", "README.md")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(md)
    print("wrote %s (%d bytes, %d examples)" % (path, len(md), len(EX.EXAMPLES)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
