# Copyright (c) 2026 Kazufumi Furuse. Licensed under the Apache License, Version 2.0 (see LICENSE).
"""AI コーディング支援への指示書を **1 つの原稿から 3 ファイル**生成する。

    AGENTS.md                      … Codex CLI ほか AGENTS.md を読む agent
    .github/copilot-instructions.md … GitHub Copilot
    GEMINI.md                      … Gemini CLI

## なぜ要るか(2026-09-15)

外部 AI(Codex / Copilot)に **文書だけ渡して op を探させる**実測をしたところ、
Codex から「リポジトリを開くだけで **検索順・`import fullseye as fs`・型連鎖・
strict 実行・検証のしかた**が分かる `AGENTS.md` がほしい」と返ってきた。実際
この repo には Claude 向けの `skills/fullseye-ops/SKILL.md` **しか**無く、
AGENTS.md / copilot-instructions.md / GEMINI.md は 1 つも無かった —— つまり
「Claude で開いたときだけ道具の使い方が分かる」状態で、他の AI から見ると
**1,946 本のノートが在ることすら分からない**。

3 ファイルを手で書くと必ず食い違う(同じ内容を 3 か所に置くのだから)。だから
**原稿は 1 つ**(このファイルの :data:`BODY`)にして、宛名だけ差し替えて出す。

## 件数は手で書かない

書いてある数は**生成時に数える**:

* op の層ごとの数 → `docs/OP_INDEX.json`(生成物。`imgevolve.py index` が書く)
* ノート・族・ガイドの数 → `docs/ops/` を**歩いて数える**(`tools/opdocs.corpus_families`)

どちらも**コミット済みの成果物から**数える。生きたレジストリから数えると、
optional backend の有無で環境ごとに違う数が出て(Linux CI は 859、手元は 901)、
drift 検査が環境差で赤くなる —— 配り物に書くべきは「**読み手が受け取るコーパスの
実数**」。数が 0 なら**生成せずに止める**(空を通す門にしない)。

    py -3.11 tools/gen_agent_files.py           # 3 ファイルを書く
    py -3.11 tools/gen_agent_files.py --check   # コミット済みと一致しなければ exit 1
"""
from __future__ import annotations

import argparse
import io
import json
import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, "tools"))

#: 出力先 → その宛名(本文は共通)。**相対パスで書く**(公開物に絶対パスを置かない)。
TARGETS = {
    "AGENTS.md": "For Codex CLI and any agent that reads `AGENTS.md`.",
    os.path.join(".github", "copilot-instructions.md"): "For GitHub Copilot.",
    "GEMINI.md": "For Gemini CLI.",
}

_HEADER = ("<!-- Generated by tools/gen_agent_files.py from one manuscript "
           "(TARGETS share BODY); do not edit by hand. -->")


class AgentFileError(RuntimeError):
    """数えられない / 数が 0(fail-closed: 書かずに止める)。"""


def facts() -> dict:
    """指示書に埋める**実数**。コミット済みの成果物から数える。"""
    idx_path = os.path.join(_ROOT, "docs", "OP_INDEX.json")
    if not os.path.exists(idx_path):
        raise AgentFileError("docs/OP_INDEX.json が無い —— 先に `imgevolve.py index` を回す")
    with io.open(idx_path, encoding="utf-8") as fh:
        idx = json.load(fh)
    tiers = idx.get("tiers") or {}
    import opdocs
    fams = opdocs.corpus_families()
    core = sum(f[1] for f in fams if f[0] in ("2d", "3d"))
    f = {
        "total": idx.get("n_ops") or 0,
        "registry": sum(tiers.get(k, 0) for k in ("registry", "color", "nary")),
        "ledger": tiers.get("ledger", 0),
        "sorts": len(idx.get("sorts") or ()),
        "notes": sum(x[1] for x in fams),
        "families": len(fams),
        "guides": sum(x[3] for x in fams),
        "core": core,
        "rest": sum(x[1] for x in fams) - core,
    }
    zero = sorted(k for k, v in f.items() if not v)
    if zero:
        raise AgentFileError(
            "数えたら 0 だった: %s —— 0 の数字を配り物に書くくらいなら止める "
            "(索引かコーパスが壊れている)" % ", ".join(zero))
    return f


#: **原稿はここ 1 つ。** 3 ファイルは宛名だけ違う。
#: `skills/fullseye-ops/SKILL.md`(Claude 向け)と同じことを言う —— 食い違ったら
#: どちらかが嘘になるので、検索順・呼び方・検証のしかたは意図的に同じ言葉で書く。
BODY = """
Fullseye is an image-processing, geometric-vision and physical-measurement library:
**{total} operators** ({registry} in the 2-D registry, {ledger} in the typed ledgers) with
**{notes} notes in {families} families** plus {guides} family guides. **The notes are the
knowledge base: retrieve first, then write code** — do not hand-roll cv2 / skimage / scipy.

## How to look something up (in this order)

1. `py -3.11 imgevolve.py ops find <word>` — scored cross-layer search (`fullseye ops ...`
   from a PyPI install); `--json` keeps stdout JSON-only. `ops describe <op>` answers in one
   shape whatever tier the op is in (naming it in `tier`); `ops path <sort> <sort>` returns
   op chains that actually connect two types.
2. `docs/CAPABILITIES.md` — indexed by *what you can do*, each entry tied to real ops.
3. `docs/ops/INDEX.md` → `docs/ops/<family>/INDEX.md` → `docs/ops/<family>/<category>/<op>.md`.
   Grep the **whole** of `docs/ops`, never one family: `2d` and `3d` hold {core} of the
   {notes} notes, so grepping only those two misses {rest}.
4. MCP client: `py -3.11 -m fullseye.mcp` (stdio) serves the same catalog.

## Calling it

```python
import fullseye as fs
out  = fs.apply(img, "otsu", 0.5, 0.5)          # 2-D registry: 1 image + 2 knobs in [0,1]
out  = fs.run_pipeline(img, ["gaussian", "sobel_amp", "otsu"])
pose = fs.op_run("icp_point2plane", src, dst)   # typed ledgers: real named arguments
fs.op_find("icp"); fs.op_path("image", "region"); fs.op_assist("<ledger op>")
```

## Types (sorts) are the contract

Every op declares `in` / `out` sorts ({sorts} sort names: image, region, color, contour,
points, pose, volume, …). Chain by type, never by guesswork: `ops path <from> <to>` (or
`fs.op_path`) enumerates chains that connect; `fs.op_assist` covers ledger ops only.

## Strict execution and the fallback ledger

Backends fail soft, so a wrapper that raises can look like a working identity op. That
degradation is recorded, not hidden: `backend_safe.fallbacks()` is the ledger, and strict mode
re-raises instead (`FULLSEYE_STRICT=1` / `IMGEVOLVE_STRICT_BACKENDS=1`). Run gates and
benchmarks strict; `fs.op_run(..., strict=True)` also turns preflight warnings into `ValueError`.

## Verify before you claim

- Every op has a worked example asserting ground truth: `py -3.11 examples/<id>.py` prints
  PASS. Run it instead of trusting a plausible-looking pipeline.
- `docs/MATURITY.md` records how far each capability is *actually* validated (most are
  `verified-synthetic`); honest-disclosure notes in docstrings are normative — never over-claim.

## On Windows shells

Docs and notes are UTF-8 **without BOM**; PowerShell reads them as the ANSI code page and
mojibakes the Japanese unless told otherwise — use `Get-Content -Encoding utf8 <file>`, and
set `PYTHONIOENCODING=utf-8` when the console running the CLI is not UTF-8.

Claude Code users: the same guidance lives as a skill in `skills/fullseye-ops/SKILL.md`.
"""


def render(target: str, f: dict) -> str:
    """1 ファイル分の本文(宛名 + 共通原稿)。"""
    return "%s\n# Fullseye — instructions for AI coding assistants\n\n%s\n%s" % (
        _HEADER, TARGETS[target], BODY.format(**f).rstrip() + "\n")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="書き込まず、コミット済みと一致するかだけ見る(exit 1 で不一致)")
    a = ap.parse_args(argv)
    f = facts()
    bad = []
    for target in sorted(TARGETS):
        path = os.path.join(_ROOT, target)
        want = render(target, f)
        if a.check:
            got = io.open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if got != want:
                bad.append(target.replace(os.sep, "/"))
            continue
        os.makedirs(os.path.dirname(path) or _ROOT, exist_ok=True)
        io.open(path, "w", encoding="utf-8", newline="\n").write(want)
    if a.check:
        if bad:
            print("drift: %s (py -3.11 tools/gen_agent_files.py で作り直す)" % ", ".join(bad))
            return 1
        print("agent files: up to date")
        return 0
    print("wrote %s (%d op / %d notes)"
          % (", ".join(sorted(t.replace(os.sep, "/") for t in TARGETS)), f["total"], f["notes"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
